Task/ntp 315 user can select an individual t ps service page
DFE-Digital/find-a-tuition-partner pull request #51
Opened 2022-07-19 10:26 UTC by stephenjmcneill

## Context

To add navigation for back and home links in the tuition partner details page

## Changes proposed in this pull request

Navigation for back and home links and end to end testing

![Screen without navigation links](https://user-images.githubusercontent.com/33860585/179726311-99421649-2b4d-4ec9-bff9-a4ee7bd77cdf.png)

![Screen without navigation links](https://user-images.githubusercontent.com/33860585/179728752-2a222f6f-5e61-442f-98bc-5bda8d5ac452.png)

## Guidance to review

Navigate to tutor partner details page and test links

Run ends to end tests for navigation links

[## Link to Jira ticket](https://dfedigital.atlassian.net/browse/NTP-315)

## Things to check

- [ ] Title is in the format "NTP-XXX: Short description" where NTP-XXX is the Jira ticket reference
- [ ] Code and tests follow the [coding standards](/docs/coding-standards.md)
- [ ] Test coverage of new code is at least 80%
- [ ] All UI related acceptance criteria specified in the ticket have been added to the relevant [cypress test feature file(s)](/UI/cypress/e2e/)
- [ ] Unless explicitly mentioned in the ticket, all UI work should have been tested as working on desktop and mobile resolutions with JavaScript on and off
- [ ] Database migrations can be applied to the current codebase in main without causing exceptions
- [ ] Debug logging has been added after all logic decision points
- [ ] All [automated testing](/README.md#testing) including accessibility and security has been run against your code

2022-07-19 11:53 UTC, benagain approved these changes

2022-07-19 13:13 UTC, iterative-it requested changes

2022-07-19 14:22 UTC, stephenjmcneill commented on UI/cypress/e2e/tuition-partner-details.js
> +    cy.url().should('eq', 'https://localhost:7036/search-results?Postcode=sk11eb&TuitionType=Any&Subjects=KeyStage1-English');
Changed to suggested fix  cy.location('search').should('eq', '?Postcode=sk11eb&TuitionType=Any&Subjects=KeyStage1-English')

2022-07-20 07:57 UTC, iterative-it approved these changes

2022-07-20 08:16 UTC, merged